spring.application.name=backend
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/learning_stack}
spring.datasource.username=${DB_USERNAME:learning_stack}
spring.datasource.password=${DB_PASSWORD:learning_stack}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
